import {
  Compass,
  Code2,
  Briefcase,
  ArrowRightLeft,
  DollarSign,
  BarChart3,
  Award,
  Zap,
  Target,
  FileCheck,
  TrendingUp,
  BookOpen,
  Calendar,
  Layers,
  Sparkles,
  Users,
  MessageSquare,
  ShieldCheck,
} from "lucide-react";
import {
  RoadmapStep,
} from "./CareerCoachTypes";

export interface TopicQuickTool {
  iconName: string;
  label: string;
  prompt: string;
}

export interface TopicQuickAction {
  id: string;
  title: string;
  subtitle: string;
  iconName: string;
  colorVariant: "blue" | "indigo" | "emerald" | "purple" | "amber";
  actionType: string;
  linkHref?: string;
}

export interface CareerCoachTopicConfig {
  id: string;
  name: string;
  tagline: string;
  iconName: string;
  category: "planning" | "development" | "growth" | "workplace";
  greeting: string;
  suggestedPrompts: { iconName: string; text: string }[];
  roadmapTitle: string;
  roadmapLevel: string;
  roadmapSteps: RoadmapStep[];
  quickTools: TopicQuickTool[];
}

export const CAREER_COACH_TOPICS: Record<string, CareerCoachTopicConfig> = {
  "career-planning": {
    id: "career-planning",
    name: "Career Planning",
    tagline: "Define goals, milestones & target roles",
    iconName: "Compass",
    category: "planning",
    greeting: "Let's map where you want your career to go and turn your long-term ambitions into clear, measurable milestones.",
    suggestedPrompts: [
      { iconName: "Target", text: "Define my 6-month career goal" },
      { iconName: "Calendar", text: "Plan my next 90-day execution goals" },
      { iconName: "TrendingUp", text: "Define criteria for my next seniority level" },
      { iconName: "Compass", text: "Assess alignment for engineering management" },
    ],
    roadmapTitle: "Career Planning Roadmap",
    roadmapLevel: "Career Direction & Milestone Execution",
    roadmapSteps: [
      {
        id: 1,
        number: "01",
        title: "Define Career Goal",
        status: "current",
        summary: "Clarify the target role, industry direction, compensation expectations, and long-term career outcomes you want to achieve.",
        deliverables: [
          "Define specific target role and seniority level",
          "Clarify preferred industry domain and company tier",
          "Set 90-day and 1-year career success objectives",
        ],
        suggestedTech: ["Career Vision Matrix", "Target Role Scorecard", "Market Benchmarks"],
        estimatedWeeks: "Weeks 1 - 2",
        completionCriteria: "Documented 1-page Career Goal and Direction scorecard.",
      },
      {
        id: 2,
        number: "02",
        title: "Assess Current Position",
        status: "upcoming",
        summary: "Audit current achievements, technical scope, leadership contributions, and existing resume baseline.",
        deliverables: [
          "Inventory of recent professional deliverables and business impact",
          "ATS resume baseline assessment using HireLens ATS Engine",
          "Evaluation of current workplace strengths and recognition",
        ],
        suggestedTech: ["HireLens ATS Analyzer", "STAR Impact Framework", "Position Audit"],
        estimatedWeeks: "Weeks 3 - 4",
        completionCriteria: "Baseline competency matrix completed across technical and leadership pillars.",
      },
      {
        id: 3,
        number: "03",
        title: "Identify Skill Gaps",
        status: "upcoming",
        summary: "Compare current capabilities against target role job requirements to isolate critical missing proficiencies.",
        deliverables: [
          "Gap analysis report prioritizing high-ROI skills",
          "Identified weak points in architecture or communication",
          "Target certifications or system design mastery list",
        ],
        suggestedTech: ["Skill Gap Parser", "Target Role Benchmarks"],
        estimatedWeeks: "Weeks 5 - 6",
        completionCriteria: "Top 3 high-impact growth priorities identified.",
      },
      {
        id: 4,
        number: "04",
        title: "Build Development Plan",
        status: "upcoming",
        summary: "Formulate a week-by-week learning and project plan with dedicated milestone checkpoints.",
        deliverables: [
          "Curated learning schedule with 5 hrs/week commitment",
          "High-visibility workplace project selection",
          "Mentor check-in schedule and progress metrics",
        ],
        suggestedTech: ["Quarterly OKRs", "Development Milestones"],
        estimatedWeeks: "Weeks 7 - 12",
        completionCriteria: "Approved 90-day action plan with scheduled milestones.",
      },
      {
        id: 5,
        number: "05",
        title: "Execute & Apply",
        status: "upcoming",
        summary: "Deliver key roadmap milestones, showcase completed projects, and update professional profiles.",
        deliverables: [
          "Execution of target technical initiative at work",
          "Refreshed resume and high-impact LinkedIn headline",
          "Strategic networking outreach to hiring managers",
        ],
        suggestedTech: ["HireLens Resume Builder", "Outreach Strategy"],
        estimatedWeeks: "Weeks 13 - 20",
        completionCriteria: "Delivered primary milestone project and initiated external/internal opportunities.",
      },
      {
        id: 6,
        number: "06",
        title: "Review & Advance",
        status: "upcoming",
        summary: "Evaluate offer letters or internal promotion cases, calibrate compensation, and establish next-level goals.",
        deliverables: [
          "Promotion dossier or multiple offer comparison sheet",
          "Final compensation negotiation execution",
          "First 90 days onboarding strategy for new level",
        ],
        suggestedTech: ["Offer Negotiation Matrix", "Career Coach Dossier"],
        estimatedWeeks: "Weeks 21 - 24",
        completionCriteria: "Signed offer or promotion confirmation meeting target compensation.",
      },
    ],
    quickTools: [
      { iconName: "Target", label: "Set 90-Day Goal", prompt: "Help me define 3 high-impact, measurable career goals for the next 90 days." },
      { iconName: "Layers", label: "Break Down Goal", prompt: "Break down my target of reaching the next seniority level into manageable monthly sprints." },
      { iconName: "Calendar", label: "Review Roadmap", prompt: "Review my current career timeline and suggest optimal milestone checkpoints." },
      { iconName: "Compass", label: "Direction Audit", prompt: "Assess whether my current project scope aligns with my long-term career ambition." },
    ],
  },

  "skill-development": {
    id: "skill-development",
    name: "Skill Development",
    tagline: "Identify skill gaps & learning paths",
    iconName: "Code2",
    category: "development",
    greeting: "Let's identify the critical technical, architectural, and leadership skills that will bridge the gap to your target role.",
    suggestedPrompts: [
      { iconName: "Code2", text: "Assess my current technical skills" },
      { iconName: "Target", text: "Find my skill gaps for target role" },
      { iconName: "Sparkles", text: "Generate an 8-week learning plan" },
      { iconName: "TrendingUp", text: "Prioritize skills with highest market ROI" },
    ],
    roadmapTitle: "Skill Development Roadmap",
    roadmapLevel: "Competency Assessment & Practical Mastery",
    roadmapSteps: [
      {
        id: 1,
        number: "01",
        title: "Assess Current Skills",
        status: "current",
        summary: "Conduct a comprehensive audit of your current programming languages, frameworks, cloud tooling, and system design strengths.",
        deliverables: [
          "Comprehensive inventory of current core skills and proficiencies",
          "Identification of proven strengths vs areas needing refresher",
          "Self-assessment benchmark against industry competency ladders",
        ],
        suggestedTech: ["Skills Matrix", "GitHub Audit", "Competency Framework"],
        estimatedWeeks: "Weeks 1 - 2",
        completionCriteria: "Completed scorecard rating proficiency across 12 core technical competencies.",
      },
      {
        id: 2,
        number: "02",
        title: "Identify Skill Gaps",
        status: "upcoming",
        summary: "Compare your current skill inventory with recurring requirements in target job descriptions to isolate critical gaps.",
        deliverables: [
          "List of missing architectural patterns, languages, or tools",
          "Analysis of testing, observability, and cloud infrastructure gaps",
          "ATS keyword alignment check across target job listings",
        ],
        suggestedTech: ["HireLens ATS Analyzer", "JD Skill Extractor"],
        estimatedWeeks: "Weeks 3 - 4",
        completionCriteria: "Top 3 highest-priority skill gaps documented with learning objectives.",
      },
      {
        id: 3,
        number: "03",
        title: "Prioritize Skills",
        status: "upcoming",
        summary: "Rank skills by hiring demand, salary multiplier, and time-to-learn efficiency to maximize your effort.",
        deliverables: [
          "ROI matrix ranking target skills by market demand",
          "Timeline estimation for reaching practical proficiency",
          "Resource selection (official docs, courses, repo sandboxes)",
        ],
        suggestedTech: ["Learning ROI Matrix", "Market Demand Reports"],
        estimatedWeeks: "Weeks 5 - 6",
        completionCriteria: "Prioritized learning curriculum containing 2 primary and 1 secondary skill.",
      },
      {
        id: 4,
        number: "04",
        title: "Build Learning Plan",
        status: "upcoming",
        summary: "Execute structured learning sprints with hands-on exercises, sandbox builds, and technical documentation.",
        deliverables: [
          "Weekly deep-dive study schedules and code katas",
          "Implementation of modern patterns and architectural principles",
          "Summary notes and reference cheat-sheets",
        ],
        suggestedTech: ["Sandbox Projects", "Technical Notes", "Code Reviews"],
        estimatedWeeks: "Weeks 7 - 12",
        completionCriteria: "Completed 3 structured modules with passing tests and verified sandbox builds.",
      },
      {
        id: 5,
        number: "05",
        title: "Apply in Practice",
        status: "upcoming",
        summary: "Apply newly acquired competencies in a production-grade application featuring real-world scale and tests.",
        deliverables: [
          "End-to-end application integrating the target technologies",
          "Automated CI/CD workflow with unit and integration tests",
          "Performance benchmarking and error monitoring integration",
        ],
        suggestedTech: ["GitHub Actions", "Docker", "Cloud Deployments"],
        estimatedWeeks: "Weeks 13 - 18",
        completionCriteria: "Public repository with comprehensive documentation and live deployment URL.",
      },
      {
        id: 6,
        number: "06",
        title: "Validate Competencies",
        status: "upcoming",
        summary: "Demonstrate verified mastery through code reviews, technical mock interviews, and resume updates.",
        deliverables: [
          "Technical interview simulation with 85%+ rating",
          "Updated resume showcasing verified technical bullet points",
          "Technical case study or architecture summary",
        ],
        suggestedTech: ["HireLens Interview Trainer", "Resume Builder"],
        estimatedWeeks: "Weeks 19 - 22",
        completionCriteria: "Successful technical mock interview and updated resume verified in ATS Analyzer.",
      },
    ],
    quickTools: [
      { iconName: "Code2", label: "Skill Gap Check", prompt: "Identify the critical skill gaps between my current stack and target role expectations." },
      { iconName: "Sparkles", label: "Learning Plan", prompt: "Create a 4-week structured curriculum to master my top priority technical skill." },
      { iconName: "Layers", label: "Project Ideas", prompt: "Suggest project architectures that demonstrate practical mastery of my new skills." },
      { iconName: "TrendingUp", label: "Skill Priority", prompt: "Which skills offer the highest market demand and compensation multiplier right now?" },
    ],
  },

  "job-search": {
    id: "job-search",
    name: "Job Search Strategy",
    tagline: "High-conversion outreach & targeting",
    iconName: "Briefcase",
    category: "growth",
    greeting: "Let's build an intentional, high-conversion job search strategy centered on targeted applications, warm outreach, and recruiter visibility.",
    suggestedPrompts: [
      { iconName: "Briefcase", text: "Define my ideal target company tier list" },
      { iconName: "Target", text: "Optimize my application and outreach cadence" },
      { iconName: "Users", text: "Create a personalized recruiter outreach script" },
      { iconName: "TrendingUp", text: "Strategies to increase screening conversion rate" },
    ],
    roadmapTitle: "Job Search Strategy Roadmap",
    roadmapLevel: "Market Targeting & Pipeline Generation",
    roadmapSteps: [
      {
        id: 1,
        number: "01",
        title: "Define Target Roles",
        status: "current",
        summary: "Narrow down specific job titles, seniority levels, target company tiers, and work location preferences.",
        deliverables: [
          "Target company tier list (Dream, Target, Safety)",
          "Specific role titles and search Boolean queries",
          "Compensation floor and remote flexibility criteria",
        ],
        suggestedTech: ["Company Tier List", "Job Search Criteria"],
        estimatedWeeks: "Weeks 1 - 2",
        completionCriteria: "List of 30 validated target companies matching core criteria.",
      },
      {
        id: 2,
        number: "02",
        title: "Optimize Profile & Resume",
        status: "upcoming",
        summary: "Align resume, cover letters, and LinkedIn profile to match target job descriptions with 85%+ ATS score.",
        deliverables: [
          "Master ATS-optimized resume tailored to primary target role",
          "High-conversion LinkedIn profile rewrite with keyword optimization",
          "Reusable modular cover letter template",
        ],
        suggestedTech: ["HireLens ATS Analyzer", "Cover Letter Generator"],
        estimatedWeeks: "Weeks 3 - 4",
        completionCriteria: "Resume achieves 85+ score in ATS Analyzer on 5 target job postings.",
      },
      {
        id: 3,
        number: "03",
        title: "Find Opportunities",
        status: "upcoming",
        summary: "Identify active and unposted opportunities using advanced filtering, talent pools, and company career portals.",
        deliverables: [
          "Daily curated job feed tracking 10 fresh postings/week",
          "Identification of hiring manager names for key roles",
          "Active alerts setup on priority company career portals",
        ],
        suggestedTech: ["HireLens Job Matcher", "Company Career Portals"],
        estimatedWeeks: "Weeks 5 - 6",
        completionCriteria: "Pipeline of 25 active target openings loaded into application tracker.",
      },
      {
        id: 4,
        number: "04",
        title: "Apply Strategically",
        status: "upcoming",
        summary: "Submit tailored applications within 48 hours of posting, accompanied by targeted recruiter touchpoints.",
        deliverables: [
          "Tailored resumes customized per high-priority opportunity",
          "Application batch tracking with response rate metrics",
          "Follow-up cadence within 5 business days",
        ],
        suggestedTech: ["Application Tracker", "Cover Letter Tool"],
        estimatedWeeks: "Weeks 7 - 10",
        completionCriteria: "20 tailored applications submitted with tracked response metrics.",
      },
      {
        id: 5,
        number: "05",
        title: "Network & Outreach",
        status: "upcoming",
        summary: "Conduct warm referral outreach to alumni, mutual connections, and engineering leaders at target companies.",
        deliverables: [
          "Personalized cold messaging scripts with 30%+ response rate",
          "Informational interview outreach to industry peers",
          "Secured internal employee referrals for top 3 dream companies",
        ],
        suggestedTech: ["LinkedIn Messaging", "Warm Intro Scripts"],
        estimatedWeeks: "Weeks 11 - 14",
        completionCriteria: "Secured at least 3 internal employee referrals.",
      },
      {
        id: 6,
        number: "06",
        title: "Track & Improve",
        status: "upcoming",
        summary: "Analyze pipeline funnel metrics (applications, screens, technical rounds) and optimize underperforming stages.",
        deliverables: [
          "Conversion funnel dashboard (Screen rate > 20%)",
          "Feedback log from recruiter phone screens",
          "Iterative keyword adjustments on resume based on response data",
        ],
        suggestedTech: ["Funnel Analytics", "Interview Trainer"],
        estimatedWeeks: "Weeks 15 - 18",
        completionCriteria: "Maintained 20%+ screen conversion rate across application pipeline.",
      },
    ],
    quickTools: [
      { iconName: "Briefcase", label: "Target Roles", prompt: "Help me identify the best role titles and company tiers based on my background." },
      { iconName: "Target", label: "Application Strategy", prompt: "What is the optimal weekly application and outreach schedule for maximum response rate?" },
      { iconName: "Users", label: "Networking Script", prompt: "Write a high-conversion outreach message to an Engineering Manager." },
      { iconName: "FileCheck", label: "Application Review", prompt: "Review my application approach and identify why my screen conversion might be low." },
    ],
  },

  "career-transitions": {
    id: "career-transitions",
    name: "Career Transitions",
    tagline: "Pivot into new domains & tech stacks",
    iconName: "ArrowRightLeft",
    category: "growth",
    greeting: "Let's map your existing professional achievements and transferable strengths into a confident, credible pivot to your new career domain.",
    suggestedPrompts: [
      { iconName: "ArrowRightLeft", text: "Map my transferable skills for my target pivot" },
      { iconName: "Target", text: "Create a 6-month career transition timeline" },
      { iconName: "Sparkles", text: "How to frame past non-traditional experience" },
      { iconName: "Briefcase", text: "Identify bridge roles for my career transition" },
    ],
    roadmapTitle: "Career Transition Roadmap",
    roadmapLevel: "Career Pivot & Transferable Value Mapping",
    roadmapSteps: [
      {
        id: 1,
        number: "01",
        title: "Define Target Career",
        status: "current",
        summary: "Clarify your current role, desired new career direction, transition motivation, and target role criteria.",
        deliverables: [
          "Clear breakdown of target role responsibilities and qualifications",
          "Assessment of motivation, risk tolerance, and realistic timeline",
          "Identification of target industry and compensation expectations",
        ],
        suggestedTech: ["Career Transition Matrix", "Role Taxonomy"],
        estimatedWeeks: "Weeks 1 - 2",
        completionCriteria: "Documented transition charter with target role requirements.",
      },
      {
        id: 2,
        number: "02",
        title: "Map Transferable Skills",
        status: "upcoming",
        summary: "Identify high-value competencies from your past career (problem solving, leadership, stakeholder comms) that translate directly.",
        deliverables: [
          "Transferable skill matrix mapping past achievements to new domain",
          "Framing past project outcomes using universal business metrics",
          "Re-phrasing domain jargon into target industry vernacular",
        ],
        suggestedTech: ["Transferable Skills Matrix", "HireLens Resume Builder"],
        estimatedWeeks: "Weeks 3 - 4",
        completionCriteria: "Documented mapping connecting 5 past achievements to target role competencies.",
      },
      {
        id: 3,
        number: "03",
        title: "Identify Hard Gaps",
        status: "upcoming",
        summary: "Isolate non-negotiable technical or operational skills required in the new field that must be acquired.",
        deliverables: [
          "Inventory of mandatory technical competencies needed",
          "Selection of accelerated training path or credential program",
          "Hands-on practice project roadmap",
        ],
        suggestedTech: ["Skill Gap Parser", "Target JDs"],
        estimatedWeeks: "Weeks 5 - 6",
        completionCriteria: "Prioritized list of 3 non-negotiable hard skill requirements.",
      },
      {
        id: 4,
        number: "04",
        title: "Build Transition Skills",
        status: "upcoming",
        summary: "Complete hands-on projects and proof-of-work that demonstrate immediate readiness in the new domain.",
        deliverables: [
          "2 end-to-end domain projects published publicly",
          "Case study highlighting domain problem solving and design tradeoffs",
          "Technical validation with industry peers",
        ],
        suggestedTech: ["Portfolio Case Study", "Public Deliverables"],
        estimatedWeeks: "Weeks 7 - 14",
        completionCriteria: "2 verified proof-of-work projects deployed with case study documentation.",
      },
      {
        id: 5,
        number: "05",
        title: "Reposition Profile",
        status: "upcoming",
        summary: "Completely rewrite your resume, LinkedIn summary, and personal narrative to lead with your new identity.",
        deliverables: [
          "Re-positioned resume leading with new domain skills and hybrid strengths",
          "Updated LinkedIn headline, summary, and featured projects",
          "Crisp 60-second elevator pitch explaining your transition narrative",
        ],
        suggestedTech: ["HireLens ATS Analyzer", "LinkedIn Optimization"],
        estimatedWeeks: "Weeks 15 - 18",
        completionCriteria: "High ATS score on target domain JDs with unified career narrative.",
      },
      {
        id: 6,
        number: "06",
        title: "Execute Transition",
        status: "upcoming",
        summary: "Launch targeted networking and application campaign targeting transition-friendly companies.",
        deliverables: [
          "Targeted outreach to companies valuing hybrid/diverse backgrounds",
          "Participation in niche communities related to target field",
          "First interviews and offer acquisition in new domain",
        ],
        suggestedTech: ["Networking Strategy", "Interview Trainer"],
        estimatedWeeks: "Weeks 19 - 24",
        completionCriteria: "Signed first job offer in target new domain.",
      },
    ],
    quickTools: [
      { iconName: "ArrowRightLeft", label: "Transferable Skills", prompt: "Analyze how my previous role experience transfers to my target career domain." },
      { iconName: "Target", label: "Gap Analysis", prompt: "What are the biggest hard skill gaps I need to close to make a credible career pivot?" },
      { iconName: "Sparkles", label: "Transition Plan", prompt: "Create a 6-month roadmap to transition from my current field into my target role." },
      { iconName: "Briefcase", label: "Elevator Pitch", prompt: "Help me write a concise 60-second elevator pitch explaining my career transition." },
    ],
  },

  "salary-negotiation": {
    id: "salary-negotiation",
    name: "Salary & Negotiation",
    tagline: "Compensation benchmarks & tactics",
    iconName: "DollarSign",
    category: "growth",
    greeting: "Let's prepare your market positioning, data-backed compensation targets, and proven negotiation talking points before you speak to recruiters.",
    suggestedPrompts: [
      { iconName: "DollarSign", text: "Understand my position and target range" },
      { iconName: "TrendingUp", text: "How to deflect early salary questions" },
      { iconName: "Target", text: "Prepare a data-backed counter-offer script" },
      { iconName: "Sparkles", text: "How to evaluate equity (RSUs vs options)" },
    ],
    roadmapTitle: "Salary & Negotiation Roadmap",
    roadmapLevel: "Offer Strategy & Negotiation Frameworks",
    roadmapSteps: [
      {
        id: 1,
        number: "01",
        title: "Understand Your Position",
        status: "current",
        summary: "Clarify your current role, scope of responsibilities, experience level, target compensation expectations, and negotiation objectives.",
        deliverables: [
          "Current compensation breakdown and baseline expectations",
          "Target walk-away minimum number and stretch compensation goal",
          "Inventory of specific business outcomes and revenue drivers delivered",
        ],
        suggestedTech: ["Position Assessment", "Impact Scorecard"],
        estimatedWeeks: "Weeks 1 - 2",
        completionCriteria: "Established target number, walk-away number, and 3 personal value drivers.",
      },
      {
        id: 2,
        number: "02",
        title: "Understand Market Range",
        status: "upcoming",
        summary: "Research verified compensation data points (base salary, annual bonus, RSU vesting, signing bonus) across target tiers.",
        deliverables: [
          "Validated 25th, 50th, and 75th percentile compensation figures",
          "Comparison of remote vs geographic tier salary bands",
          "Clear breakdown of base vs variable equity components",
        ],
        suggestedTech: ["Market Benchmarks", "Compensation Data"],
        estimatedWeeks: "Weeks 3 - 4",
        completionCriteria: "Validated compensation benchmarks across target company tiers.",
      },
      {
        id: 3,
        number: "03",
        title: "Recruiter Phone Strategy",
        status: "upcoming",
        summary: "Safely navigate early compensation questions from recruiters without anchoring yourself prematurely.",
        deliverables: [
          "Rehearsed deflection scripts for early salary expectation questions",
          "Framework for anchoring high when forced to give a range",
          "Questions to ask recruiter about role level and band scope",
        ],
        suggestedTech: ["Deflection Scripts", "Screening Rehearsal"],
        estimatedWeeks: "Weeks 5 - 6",
        completionCriteria: "Successfully navigate recruiter phone screens without revealing premature salary figures.",
      },
      {
        id: 4,
        number: "04",
        title: "Prepare Negotiation Case",
        status: "upcoming",
        summary: "Draft professional counter-offer scripts and data-driven business justifications upon receiving initial verbal offer.",
        deliverables: [
          "Custom counter-offer email script addressing base and equity",
          "Justification document linking target compensation to business value",
          "Alternative ask matrix (signing bonus, extra PTO, accelerated review)",
        ],
        suggestedTech: ["Negotiation Templates", "Counter-Offer Script"],
        estimatedWeeks: "Weeks 7 - 8",
        completionCriteria: "Formal counter-offer response drafted with 2 fallback negotiation levers.",
      },
      {
        id: 5,
        number: "05",
        title: "Handle the Conversation",
        status: "upcoming",
        summary: "Conduct the live verbal negotiation call with warmth, enthusiasm, and firmness.",
        deliverables: [
          "Rehearsed live talking points with collaborative tone",
          "Responses prepared for common recruiter pushback phrases",
          "Confirmation in writing of all agreed terms",
        ],
        suggestedTech: ["Live Call Scripts", "HireLens Interview Trainer"],
        estimatedWeeks: "Weeks 9 - 10",
        completionCriteria: "Live negotiation call executed with updated written revised offer.",
      },
      {
        id: 6,
        number: "06",
        title: "Evaluate & Sign",
        status: "upcoming",
        summary: "Review total reward breakdown, legal terms, non-compete clauses, and benefits before final signature.",
        deliverables: [
          "Total compensation calculation across 4-year vesting timeline",
          "Review of health, retirement match, and remote stipend benefits",
          "Executed offer letter and start date agreement",
        ],
        suggestedTech: ["Total Rewards Calculator", "Offer Checklist"],
        estimatedWeeks: "Weeks 11 - 12",
        completionCriteria: "Signed offer meeting or exceeding target compensation benchmark.",
      },
    ],
    quickTools: [
      { iconName: "DollarSign", label: "Salary Benchmark", prompt: "What is the typical compensation range for my role and seniority level?" },
      { iconName: "TrendingUp", label: "Negotiation Prep", prompt: "Write a polite counter-offer script requesting an increase in base and sign-on bonus." },
      { iconName: "Target", label: "Offer Review", prompt: "Help me evaluate the pros and cons of an offer consisting of base, bonus, and equity." },
      { iconName: "Sparkles", label: "Talking Points", prompt: "What are the best verbal talking points to use when a recruiter pushes for salary expectations?" },
    ],
  },

  "industry-insights": {
    id: "industry-insights",
    name: "Industry Insights",
    tagline: "Market trends, hiring demands & AI impact",
    iconName: "BarChart3",
    category: "planning",
    greeting: "Let's analyze the shifting industry landscape, emerging engineering disciplines, and market demand patterns to future-proof your career trajectory.",
    suggestedPrompts: [
      { iconName: "BarChart3", text: "Analyze demand trends in my target industry" },
      { iconName: "TrendingUp", text: "How AI workflows are shifting role expectations" },
      { iconName: "Target", text: "Which tech specializations have highest budget growth" },
      { iconName: "Sparkles", text: "How to future-proof my skill set over 3 years" },
    ],
    roadmapTitle: "Industry Insights Roadmap",
    roadmapLevel: "Market Intelligence & Future-Proofing",
    roadmapSteps: [
      {
        id: 1,
        number: "01",
        title: "Understand Your Industry",
        status: "current",
        summary: "Identify your target sector (Cloud, AI Systems, Enterprise SaaS, FinTech), capital allocation trends, and key hiring drivers.",
        deliverables: [
          "Sector overview highlighting top hiring domains and tech investments",
          "Analysis of legacy skills vs high-growth competencies",
          "Mapping of target employer landscape across market sectors",
        ],
        suggestedTech: ["Industry Overview", "Market Analysis"],
        estimatedWeeks: "Weeks 1 - 2",
        completionCriteria: "Documented sector profile with identified growth areas.",
      },
      {
        id: 2,
        number: "02",
        title: "Identify Trends",
        status: "upcoming",
        summary: "Track the impact of AI developer tools, distributed architecture changes, and evolving seniority standards.",
        deliverables: [
          "Assessment of AI automation impact on daily engineering workflows",
          "Shift from manual coding toward architecture and system design ownership",
          "Demand profile for full-stack vs deep specialist roles",
        ],
        suggestedTech: ["Industry Reports", "Architecture Trends"],
        estimatedWeeks: "Weeks 3 - 4",
        completionCriteria: "Documented 5 key trends impacting your target role over the next 24 months.",
      },
      {
        id: 3,
        number: "03",
        title: "Track Emerging Skills",
        status: "upcoming",
        summary: "Isolate emerging libraries, cloud services, and paradigms gaining rapid enterprise adoption.",
        deliverables: [
          "Watchlist of high-momentum open-source frameworks and tools",
          "Evaluation of cloud cost optimization and security best practices",
          "Hands-on experimentation with modern developer toolchains",
        ],
        suggestedTech: ["Tech Radar", "GitHub Trending"],
        estimatedWeeks: "Weeks 5 - 8",
        completionCriteria: "Experimentation with 2 high-growth frameworks completed.",
      },
      {
        id: 4,
        number: "04",
        title: "Compare Role Demand",
        status: "upcoming",
        summary: "Benchmark open headcount, interview difficulty, and compensation differentials across target companies.",
        deliverables: [
          "Headcount volume comparison across 20 target employers",
          "Interview requirement shift analysis (take-homes vs system design)",
          "Salary premium matrix for emerging skills",
        ],
        suggestedTech: ["HireLens Job Matcher", "Compensation Indexes"],
        estimatedWeeks: "Weeks 9 - 12",
        completionCriteria: "Identified top 2 roles with highest ratio of open headcount to applicant competition.",
      },
      {
        id: 5,
        number: "05",
        title: "Adapt Your Profile",
        status: "upcoming",
        summary: "Update your technical vocabulary and project proof points to reflect modern industry paradigms.",
        deliverables: [
          "Resume refresh reflecting modern architectural principles",
          "Public project demonstrating modern cloud/AI workflow integration",
          "Thought leadership summary on emerging technical trends",
        ],
        suggestedTech: ["HireLens Resume Builder", "ATS Analyzer"],
        estimatedWeeks: "Weeks 13 - 18",
        completionCriteria: "Profile aligned with top 90th percentile industry trend standards.",
      },
      {
        id: 6,
        number: "06",
        title: "Plan Next Move",
        status: "upcoming",
        summary: "Execute strategic career positioning to secure high-growth opportunities before market saturation.",
        deliverables: [
          "Targeted applications to high-growth teams",
          "Secured offers at companies pioneering target technologies",
          "Long-term 3-year market position established",
        ],
        suggestedTech: ["Career Strategy", "Target Pipeline"],
        estimatedWeeks: "Weeks 19 - 24",
        completionCriteria: "Position secured within top-tier high-growth organization.",
      },
    ],
    quickTools: [
      { iconName: "BarChart3", label: "Trend Analysis", prompt: "What are the most significant architecture and tooling shifts happening in tech?" },
      { iconName: "TrendingUp", label: "Skill Trends", prompt: "Which technical skills are experiencing the fastest hiring growth?" },
      { iconName: "Target", label: "Role Research", prompt: "How is the role of Senior Engineer evolving with modern AI systems?" },
      { iconName: "Sparkles", label: "Career Impact", prompt: "How can I future-proof my career against automation over the next 5 years?" },
    ],
  },

  "personal-branding": {
    id: "personal-branding",
    name: "Personal Branding",
    tagline: "LinkedIn, portfolios & visibility",
    iconName: "Award",
    category: "development",
    greeting: "Let's turn your professional profiles, portfolio artifacts, and public work into a magnet for top recruiters and hiring managers.",
    suggestedPrompts: [
      { iconName: "Award", text: "Define my unique professional value proposition" },
      { iconName: "Target", text: "Optimize my LinkedIn headline for inbound recruiter reach" },
      { iconName: "Users", text: "Structure portfolio case studies that prove impact" },
      { iconName: "Sparkles", text: "How to showcase GitHub projects for recruiters" },
    ],
    roadmapTitle: "Personal Branding Roadmap",
    roadmapLevel: "Online Presence & Professional Visibility",
    roadmapSteps: [
      {
        id: 1,
        number: "01",
        title: "Define Professional Position",
        status: "current",
        summary: "Clarify your target professional identity, primary audience, core strengths, and unique value proposition.",
        deliverables: [
          "1-sentence value proposition headline",
          "Target audience definition (recruiter vs founder vs engineering manager)",
          "Consistent bio and professional photo across all profiles",
        ],
        suggestedTech: ["Brand Statement", "Value Proposition Matrix"],
        estimatedWeeks: "Weeks 1 - 2",
        completionCriteria: "Documented professional positioning statement tailored to target roles.",
      },
      {
        id: 2,
        number: "02",
        title: "Optimize LinkedIn",
        status: "upcoming",
        summary: "Transform your LinkedIn profile with keyword-dense summaries, quantifiable experience bullets, and social proof.",
        deliverables: [
          "Keyword-rich LinkedIn headline and 'About' narrative section",
          "Experience section formatted with STAR impact bullet points",
          "Featured section with links to top live projects and articles",
        ],
        suggestedTech: ["LinkedIn SEO", "HireLens ATS Keywords"],
        estimatedWeeks: "Weeks 3 - 4",
        completionCriteria: "100% LinkedIn All-Star profile score with 3+ recommendations.",
      },
      {
        id: 3,
        number: "03",
        title: "Build Portfolio",
        status: "upcoming",
        summary: "Create a modern, clean portfolio website highlighting your best work with live demos and metrics.",
        deliverables: [
          "Minimalist, fast portfolio website with clear structure",
          "Case study pages for top 2 flagship deliverables",
          "Direct call to action for recruiter contact and resume download",
        ],
        suggestedTech: ["Portfolio Site", "Live Demos"],
        estimatedWeeks: "Weeks 5 - 8",
        completionCriteria: "Live portfolio domain with mobile responsiveness and demo links.",
      },
      {
        id: 4,
        number: "04",
        title: "Showcase Projects",
        status: "upcoming",
        summary: "Structure your public repositories with clean READMEs, architectural diagrams, and video walkthroughs.",
        deliverables: [
          "Professional GitHub profile README with pinned flagship repos",
          "Detailed project READMEs with architecture diagrams and API docs",
          "Short demo walkthrough for each featured project",
        ],
        suggestedTech: ["GitHub Markdown", "Architecture Diagrams"],
        estimatedWeeks: "Weeks 9 - 12",
        completionCriteria: "Pinned repos with 100% complete documentation and demo video.",
      },
      {
        id: 5,
        number: "05",
        title: "Publish & Share",
        status: "upcoming",
        summary: "Share technical insights, architecture lessons, and project milestones on LinkedIn and tech communities.",
        deliverables: [
          "2 technical deep-dive articles or case studies published",
          "Consistent weekly presence sharing learnings on LinkedIn",
          "Engagement with engineering leaders and community discussions",
        ],
        suggestedTech: ["Technical Articles", "Community Engagement"],
        estimatedWeeks: "Weeks 13 - 18",
        completionCriteria: "Published 2 technical case studies with public engagement.",
      },
      {
        id: 6,
        number: "06",
        title: "Build Inbound Flow",
        status: "upcoming",
        summary: "Convert profile visits into consistent weekly inbound recruiter messages and interview opportunities.",
        deliverables: [
          "Tracking inbound recruiter message volume (target: 3+/week)",
          "Established relationship with specialized tech recruiters",
          "Sustained organic professional reputation",
        ],
        suggestedTech: ["Inbound Pipeline", "Recruiter Network"],
        estimatedWeeks: "Weeks 19 - 24",
        completionCriteria: "Receiving consistent organic inbound recruiter inquiries weekly.",
      },
    ],
    quickTools: [
      { iconName: "Award", label: "Profile Review", prompt: "Critique my LinkedIn headline and suggest improvements for recruiter visibility." },
      { iconName: "Target", label: "Portfolio Check", prompt: "What are the essential elements a strong developer portfolio must include?" },
      { iconName: "Layers", label: "Project Positioning", prompt: "How can I describe my projects so they highlight architectural ownership?" },
      { iconName: "Sparkles", label: "LinkedIn Strategy", prompt: "Give me 5 high-impact technical topics I can write about on LinkedIn this month." },
    ],
  },

  "workplace-success": {
    id: "workplace-success",
    name: "Workplace Success",
    tagline: "Promotion, leadership & stakeholder management",
    iconName: "Zap",
    category: "workplace",
    greeting: "Let's turn your day-to-day contributions into high-visibility impact, strategic influence, and a compelling case for promotion.",
    suggestedPrompts: [
      { iconName: "Zap", text: "Clarify manager expectations for promotion" },
      { iconName: "Users", text: "Frameworks for managing difficult stakeholders" },
      { iconName: "TrendingUp", text: "How to communicate technical tradeoffs to leadership" },
      { iconName: "Award", text: "Ways to demonstrate leadership without an official title" },
    ],
    roadmapTitle: "Workplace Success Roadmap",
    roadmapLevel: "Internal Influence & Executive Visibility",
    roadmapSteps: [
      {
        id: 1,
        number: "01",
        title: "Understand Your Position",
        status: "current",
        summary: "Audit current responsibilities, manager expectations, feedback history, strengths, and specific promotion criteria.",
        deliverables: [
          "Documented career ladder rubric for your target title",
          "Alignment conversation with your manager on promotion criteria",
          "Quarterly review success metrics established",
        ],
        suggestedTech: ["Career Rubric", "1-on-1 Alignment"],
        estimatedWeeks: "Weeks 1 - 2",
        completionCriteria: "Explicit written alignment with manager on promotion requirements.",
      },
      {
        id: 2,
        number: "02",
        title: "Improve Communication",
        status: "upcoming",
        summary: "Refine written and verbal updates to lead with business outcomes rather than implementation minutiae.",
        deliverables: [
          "Concise weekly progress summaries focused on velocity and impact",
          "RFC / design document writing framework adoption",
          "Proactive cross-functional communication habits",
        ],
        suggestedTech: ["RFC Templates", "Executive Summary Format"],
        estimatedWeeks: "Weeks 3 - 6",
        completionCriteria: "Delivered 2 approved technical RFCs with cross-team sign-off.",
      },
      {
        id: 3,
        number: "03",
        title: "Build Relationships",
        status: "upcoming",
        summary: "Develop strong working relationships with product managers, QA, DevOps, and adjacent engineering squads.",
        deliverables: [
          "Bi-weekly syncs with key product and design counterparts",
          "Collaborative cross-team problem solving initiatives",
          "Peer recognition and reciprocal support system",
        ],
        suggestedTech: ["Stakeholder Mapping", "Collaboration Tools"],
        estimatedWeeks: "Weeks 7 - 10",
        completionCriteria: "Identified and partnered with 3 key cross-functional champions.",
      },
      {
        id: 4,
        number: "04",
        title: "Increase Ownership",
        status: "upcoming",
        summary: "Take full end-to-end responsibility for critical services, incident resolution, and architectural improvements.",
        deliverables: [
          "Ownership of major architectural module or release cycle",
          "Lead on-call post-mortem remediation and reliability improvements",
          "Mentorship of junior and mid-level engineers",
        ],
        suggestedTech: ["Incident Post-Mortems", "System Reliability"],
        estimatedWeeks: "Weeks 11 - 16",
        completionCriteria: "Successfully led critical multi-week technical initiative from design to release.",
      },
      {
        id: 5,
        number: "05",
        title: "Demonstrate Impact",
        status: "upcoming",
        summary: "Maintain a continuous 'Brag Document' quantifying how your work accelerated business goals or reduced costs.",
        deliverables: [
          "Quantified impact log tracking latency improvements, revenue, or team hours saved",
          "Documented mentorship contributions and onboarding improvements",
          "Peer and stakeholder endorsements collected",
        ],
        suggestedTech: ["Impact Tracker", "Brag Document Template"],
        estimatedWeeks: "Weeks 17 - 20",
        completionCriteria: "Completed Brag Document detailing quantifiable business outcomes and team impact.",
      },
      {
        id: 6,
        number: "06",
        title: "Promotion Dossier",
        status: "upcoming",
        summary: "Compile and present your comprehensive promotion case to leadership ahead of the formal review cycle.",
        deliverables: [
          "Finalized promotion packet aligned with company rubric",
          "Manager sponsorship secured with executive sign-off",
          "Celebration of confirmed level advancement and new title",
        ],
        suggestedTech: ["Promotion Packet", "Career Coach Dossier"],
        estimatedWeeks: "Weeks 21 - 24",
        completionCriteria: "Confirmed promotion to next seniority title with compensation adjustment.",
      },
    ],
    quickTools: [
      { iconName: "Zap", label: "Communication Coach", prompt: "How can I present a complex technical refactor to my Product Manager so they approve the roadmap time?" },
      { iconName: "Users", label: "Leadership Skills", prompt: "What are the most effective ways to mentor peers without slowing down sprint delivery?" },
      { iconName: "Target", label: "Promotion Plan", prompt: "Help me structure my Brag Document for my upcoming annual promotion review." },
      { iconName: "ShieldCheck", label: "Workplace Strategy", prompt: "How to handle conflicting priorities between two managers gracefully?" },
    ],
  },
};
