import { ResumeVersionItem } from "./HistoryTypes";

export const SAMPLE_RESUME_VERSIONS: ResumeVersionItem[] = [
  {
    id: "ver-1",
    title: "Senior Frontend Engineer Resume",
    roleTitle: "Senior Frontend Engineer",
    template: "modern",
    atsScore: 92,
    isAtsOptimized: true,
    isCustomTemplate: false,
    isStarred: true,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL", "Redux"],
    updatedAt: "2 hours ago",
    createdAt: "Sep 15, 2026",
    viewsCount: 142,
    downloadsCount: 16,
    resumeData: {
      id: "ver-1",
      title: "Senior Frontend Engineer Resume",
      template: "modern",
      personalInfo: {
        fullName: "Alex Morgan",
        email: "alex.morgan@example.com",
        phone: "+1 (555) 234-5678",
        location: "San Francisco, CA",
        portfolioUrl: "https://alexmorgan.dev",
        linkedinUrl: "https://linkedin.com/in/alexmorgan-dev",
        summary:
          "High-impact Senior Frontend Engineer with 6+ years building scalable design systems, Next.js web applications, and real-time collaboration tools. Proven track record boosting core web vitals by 40% and mentoring 8+ junior and mid-level engineers.",
      },
      experience: [
        {
          id: "exp-1",
          company: "Vercel Scale Partners",
          position: "Lead Frontend Architect",
          startDate: "2023-01",
          endDate: "Present",
          current: true,
          description:
            "• Architected micro-frontend component registry serving 2.5M daily active developers.\n• Reduced bundle size by 38% via dynamic tree-shaking and module boundary isolation.\n• Spearheaded accessibility (WCAG 2.1 AA) compliance across enterprise UI modules.",
        },
        {
          id: "exp-2",
          company: "Stripe Flow Inc",
          position: "Senior React Engineer",
          startDate: "2020-03",
          endDate: "2022-12",
          current: false,
          description:
            "• Engineered checkout onboarding funnel resulting in 18% conversion improvement.\n• Built end-to-end testing matrix using Playwright and Jest achieving 94% code coverage.",
        },
      ],
      education: [
        {
          id: "edu-1",
          institution: "University of California, Berkeley",
          degree: "B.S. in Computer Science",
          fieldOfStudy: "Software Engineering & HCI",
          startDate: "2016-08",
          endDate: "2020-05",
          gpa: "3.85",
        },
      ],
      skills: [
        { id: "sk-1", name: "React", level: "Expert" },
        { id: "sk-2", name: "TypeScript", level: "Expert" },
        { id: "sk-3", name: "Next.js", level: "Expert" },
        { id: "sk-4", name: "Tailwind CSS", level: "Expert" },
        { id: "sk-5", name: "GraphQL", level: "Intermediate" },
        { id: "sk-6", name: "Node.js", level: "Intermediate" },
      ],
      projects: [
        {
          id: "proj-1",
          name: "DevSprint Canvas",
          description: "Real-time collaborative kanban and whiteboard with CRDT sync engine and WebSockets.",
          githubUrl: "https://github.com/alexmorgan/devsprint",
        },
      ],
      achievements: [
        {
          id: "ach-1",
          title: "1st Place Hackathon Winner",
          description: "Global Web Performance Challenge 2024",
        },
        {
          id: "ach-2",
          title: "Author of Modern React Performance",
          description: "Newsletter read by 14k engineering subscribers",
        },
      ],
      certifications: [
        {
          id: "cert-1",
          name: "AWS Certified Cloud Practitioner",
          issuer: "Amazon Web Services",
          year: "2024",
        },
        {
          id: "cert-2",
          name: "Meta Front-End Developer Specialization",
          issuer: "Meta",
          year: "2023",
        },
      ],
    },
  },
  {
    id: "ver-2",
    title: "Full Stack AI Engineer Draft",
    roleTitle: "Full Stack AI Engineer",
    template: "professional",
    atsScore: 86,
    isAtsOptimized: true,
    isCustomTemplate: false,
    isStarred: true,
    skills: ["Python", "FastAPI", "Next.js", "LangChain", "PostgreSQL", "Docker"],
    updatedAt: "1 day ago",
    createdAt: "Sep 10, 2026",
    viewsCount: 88,
    downloadsCount: 7,
    resumeData: {
      id: "ver-2",
      title: "Full Stack AI Engineer Draft",
      template: "professional",
      personalInfo: {
        fullName: "Alex Morgan",
        email: "alex.morgan@example.com",
        phone: "+1 (555) 234-5678",
        location: "San Francisco, CA",
        portfolioUrl: "https://alexmorgan.dev",
        linkedinUrl: "https://linkedin.com/in/alexmorgan-dev",
        summary:
          "Full Stack Engineer specialized in generative AI pipelines, LLM fine-tuning, and low-latency REST/GraphQL microservices. Experienced in deploying containerized agentic systems to production Kubernetes clusters.",
      },
      experience: [
        {
          id: "exp-1",
          company: "CognitiveAI Labs",
          position: "Senior AI Full Stack Engineer",
          startDate: "2022-06",
          endDate: "Present",
          current: true,
          description:
            "• Implemented RAG search engine indexed across 10M internal enterprise documents with sub-200ms latency.\n• Designed multi-agent orchestrator with asynchronous message queues and human-in-the-loop review.",
        },
      ],
      education: [
        {
          id: "edu-1",
          institution: "University of California, Berkeley",
          degree: "B.S. in Computer Science",
          fieldOfStudy: "Machine Learning & Systems",
          startDate: "2016-08",
          endDate: "2020-05",
          gpa: "3.85",
        },
      ],
      skills: [
        { id: "sk-1", name: "Python", level: "Expert" },
        { id: "sk-2", name: "FastAPI", level: "Expert" },
        { id: "sk-3", name: "PyTorch", level: "Intermediate" },
        { id: "sk-4", name: "LangChain", level: "Expert" },
        { id: "sk-5", name: "PostgreSQL", level: "Intermediate" },
        { id: "sk-6", name: "Docker", level: "Intermediate" },
      ],
      projects: [
        {
          id: "proj-1",
          name: "NeuralDoc Assistant",
          description: "Autonomous document synthesis agent with source citation and vector embedding search.",
          githubUrl: "https://github.com/alexmorgan/neuraldoc",
        },
      ],
      achievements: [
        {
          id: "ach-1",
          title: "Published Researcher",
          description: "Published paper on semantic retrieval optimization at CVPR Workshop 2025",
        },
      ],
      certifications: [
        {
          id: "cert-1",
          name: "Google Cloud Professional ML Engineer",
          issuer: "Google Cloud",
          year: "2024",
        },
      ],
    },
  },
  {
    id: "ver-3",
    title: "Product Engineer - Minimalist",
    roleTitle: "Staff Product Engineer",
    template: "minimalist",
    atsScore: 78,
    isAtsOptimized: false,
    isCustomTemplate: true,
    isStarred: false,
    skills: ["Product Strategy", "React", "TypeScript", "Node.js", "SQL", "A/B Testing"],
    updatedAt: "3 days ago",
    createdAt: "Aug 28, 2026",
    viewsCount: 45,
    downloadsCount: 3,
    resumeData: {
      id: "ver-3",
      title: "Product Engineer - Minimalist",
      template: "minimalist",
      personalInfo: {
        fullName: "Alex Morgan",
        email: "alex.morgan@example.com",
        phone: "+1 (555) 234-5678",
        location: "San Francisco, CA",
        portfolioUrl: "https://alexmorgan.dev",
        linkedinUrl: "https://linkedin.com/in/alexmorgan-dev",
        summary:
          "Staff Product Engineer focused on user activation, rapid prototyping, and end-to-end product delivery. Bridging high-fidelity design with robust distributed backend architectures.",
      },
      experience: [
        {
          id: "exp-1",
          company: "HyperGrowth SaaS",
          position: "Staff Product Engineer",
          startDate: "2021-04",
          endDate: "2023-01",
          current: false,
          description:
            "• Led cross-functional squad of 6 engineers and 2 designers delivering core workspace sharing features.\n• Increased Day-30 user retention from 22% to 37% across 150k monthly active accounts.",
        },
      ],
      education: [
        {
          id: "edu-1",
          institution: "University of California, Berkeley",
          degree: "B.S. in Computer Science",
          fieldOfStudy: "Computer Science",
          startDate: "2016-08",
          endDate: "2020-05",
          gpa: "3.85",
        },
      ],
      skills: [
        { id: "sk-1", name: "Product Strategy", level: "Expert" },
        { id: "sk-2", name: "React", level: "Expert" },
        { id: "sk-3", name: "TypeScript", level: "Expert" },
        { id: "sk-4", name: "Node.js", level: "Intermediate" },
        { id: "sk-5", name: "SQL", level: "Intermediate" },
      ],
      projects: [],
      achievements: [
        {
          id: "ach-1",
          title: "Top Product Contributor",
          description: "Delivered 12 consecutive on-time feature launches impacting $4M ARR",
        },
      ],
      certifications: [],
    },
  },
  {
    id: "ver-4",
    title: "Startup Founding Engineer Resume",
    roleTitle: "Founding Engineer",
    template: "modern",
    atsScore: 74,
    isAtsOptimized: false,
    isCustomTemplate: false,
    isStarred: false,
    skills: ["Full Stack", "System Architecture", "React Native", "Go", "AWS", "CI/CD"],
    updatedAt: "1 week ago",
    createdAt: "Aug 14, 2026",
    viewsCount: 26,
    downloadsCount: 1,
    resumeData: {
      id: "ver-4",
      title: "Startup Founding Engineer Resume",
      template: "modern",
      personalInfo: {
        fullName: "Alex Morgan",
        email: "alex.morgan@example.com",
        phone: "+1 (555) 234-5678",
        location: "San Francisco, CA",
        portfolioUrl: "https://alexmorgan.dev",
        linkedinUrl: "https://linkedin.com/in/alexmorgan-dev",
        summary:
          "Entrepreneurial full-stack developer with 0-to-1 building experience. Specialized in rapid prototyping, resilient backend infrastructure, and multi-platform mobile client releases.",
      },
      experience: [
        {
          id: "exp-1",
          company: "Stealth FinTech",
          position: "Founding Engineer (Employee #2)",
          startDate: "2020-01",
          endDate: "2021-03",
          current: false,
          description:
            "• Built MVP from ground zero in 10 weeks, enabling seed funding round of $3.2M.\n• Set up automated CI/CD pipeline on AWS reducing deployment cycle from days to 8 minutes.",
        },
      ],
      education: [
        {
          id: "edu-1",
          institution: "University of California, Berkeley",
          degree: "B.S. in Computer Science",
          fieldOfStudy: "Computer Science",
          startDate: "2016-08",
          endDate: "2020-05",
          gpa: "3.85",
        },
      ],
      skills: [
        { id: "sk-1", name: "Full Stack", level: "Expert" },
        { id: "sk-2", name: "Go", level: "Intermediate" },
        { id: "sk-3", name: "React Native", level: "Intermediate" },
        { id: "sk-4", name: "AWS", level: "Intermediate" },
      ],
      projects: [],
      achievements: [],
      certifications: [],
    },
  },
  {
    id: "ver-5",
    title: "Technical Lead & Engineering Manager",
    roleTitle: "Engineering Manager",
    template: "professional",
    atsScore: 81,
    isAtsOptimized: true,
    isCustomTemplate: true,
    isStarred: false,
    skills: ["Team Leadership", "Hiring", "Agile", "System Design", "Budgeting", "Mentorship"],
    updatedAt: "2 weeks ago",
    createdAt: "Jul 29, 2026",
    viewsCount: 11,
    downloadsCount: 1,
    resumeData: {
      id: "ver-5",
      title: "Technical Lead & Engineering Manager",
      template: "professional",
      personalInfo: {
        fullName: "Alex Morgan",
        email: "alex.morgan@example.com",
        phone: "+1 (555) 234-5678",
        location: "San Francisco, CA",
        portfolioUrl: "https://alexmorgan.dev",
        linkedinUrl: "https://linkedin.com/in/alexmorgan-dev",
        summary:
          "Engineering leader with deep technical roots and passion for people development. Scaled engineering teams from 4 to 22 while upholding a high-velocity culture and continuous delivery practices.",
      },
      experience: [
        {
          id: "exp-1",
          company: "Nexus Cloud Systems",
          position: "Engineering Manager - Platform UI",
          startDate: "2023-02",
          endDate: "Present",
          current: true,
          description:
            "• Managed team of 10 senior and staff engineers across 3 time zones.\n• Reduced sprint cycle slippage by 35% through streamlined sprint grooming and OKR alignment.",
        },
      ],
      education: [
        {
          id: "edu-1",
          institution: "University of California, Berkeley",
          degree: "B.S. in Computer Science",
          fieldOfStudy: "Computer Science & Business Administration",
          startDate: "2016-08",
          endDate: "2020-05",
          gpa: "3.85",
        },
      ],
      skills: [
        { id: "sk-1", name: "Team Leadership", level: "Expert" },
        { id: "sk-2", name: "Technical Hiring", level: "Expert" },
        { id: "sk-3", name: "System Design", level: "Expert" },
        { id: "sk-4", name: "Agile Coaching", level: "Intermediate" },
      ],
      projects: [],
      achievements: [
        {
          id: "ach-1",
          title: "Zero Involuntary Attrition",
          description: "Maintained 0% involuntary attrition over 24 consecutive months",
        },
      ],
      certifications: [
        {
          id: "cert-1",
          name: "Certified ScrumMaster (CSM)",
          issuer: "Scrum Alliance",
          year: "2023",
        },
      ],
    },
  },
];
