import { JobListing } from "./JobTypes";

export const DEMO_JOB_LISTINGS: JobListing[] = [
  {
    id: "job-1",
    title: "Senior Frontend Engineer",
    company: "Razorpay",
    companyInitials: "RZ",
    companyColor: "from-blue-600 to-indigo-700",
    location: "Bengaluru, India",
    workMode: "Hybrid",
    jobType: "Full-time",
    salaryRange: "₹18–26 LPA",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    matchScore: 94,
    isBestMatch: true,
    postedDate: "2 days ago",
    experienceLevel: "Senior",
    companyType: "Product",
    description: "Build scalable payments UI architectures, optimize checkout Core Web Vitals, and collaborate with cross-functional product design teams."
  },
  {
    id: "job-2",
    title: "Full Stack Developer",
    company: "Zepto",
    companyInitials: "ZP",
    companyColor: "from-purple-600 to-pink-600",
    location: "Mumbai, India",
    workMode: "On-site",
    jobType: "Full-time",
    salaryRange: "₹14–20 LPA",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    matchScore: 88,
    postedDate: "1 day ago",
    experienceLevel: "Mid Level",
    companyType: "Startup",
    description: "Deliver high-velocity 10-minute delivery dispatch services and micro-frontend customer web apps."
  },
  {
    id: "job-3",
    title: "Software Engineer - UI Platform",
    company: "Swiggy",
    companyInitials: "SW",
    companyColor: "from-amber-500 to-orange-600",
    location: "Bengaluru, India",
    workMode: "Hybrid",
    jobType: "Full-time",
    salaryRange: "₹16–24 LPA",
    skills: ["JavaScript", "React", "Redux Toolkit", "CSS3"],
    matchScore: 91,
    isBestMatch: true,
    postedDate: "3 days ago",
    experienceLevel: "Mid Level",
    companyType: "Product",
    description: "Design and maintain Swiggy's design system, consumer web portals, and performance-critical frontend infrastructure."
  },
  {
    id: "job-4",
    title: "Lead Frontend Architect",
    company: "CRED",
    companyInitials: "CR",
    companyColor: "from-slate-700 to-slate-900",
    location: "Bengaluru, India",
    workMode: "On-site",
    jobType: "Full-time",
    salaryRange: "₹30–45 LPA",
    skills: ["Next.js", "GraphQL", "Web Performance", "System Design"],
    matchScore: 85,
    postedDate: "5 days ago",
    experienceLevel: "Lead",
    companyType: "Product",
    description: "Lead technical roadmap for member-only fintech web experiences, smooth animations, and high security client workflows."
  },
  {
    id: "job-5",
    title: "Product Engineer (Frontend)",
    company: "Postman",
    companyInitials: "PM",
    companyColor: "from-orange-500 to-red-600",
    location: "Remote",
    workMode: "Remote",
    jobType: "Full-time",
    salaryRange: "₹20–28 LPA",
    skills: ["React", "TypeScript", "REST APIs", "Jest"],
    matchScore: 89,
    postedDate: "Just now",
    experienceLevel: "Senior",
    companyType: "Enterprise",
    description: "Develop developer-first API collaboration tooling, browser extensions, and developer documentation workspaces."
  },
  {
    id: "job-6",
    title: "Frontend Specialist",
    company: "Flipkart",
    companyInitials: "FK",
    companyColor: "from-yellow-500 to-amber-600",
    location: "Bengaluru, India",
    workMode: "Hybrid",
    jobType: "Full-time",
    salaryRange: "₹15–22 LPA",
    skills: ["React", "HTML5", "CSS3", "Core Web Vitals"],
    matchScore: 82,
    postedDate: "1 week ago",
    experienceLevel: "Mid Level",
    companyType: "Enterprise",
    description: "Scale e-commerce storefronts across mobile web and desktop, optimizing conversion and rendering metrics."
  }
];
